# Publish to Maven Central

name: publish

on:
  repository_dispatch:
    types: manual-publish
# once all is working, trigger when release is created
#  release:
#    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install gpg secret key
        run: |
        cat <(echo -e "${{ secrets.SEER_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
#      - name: Build with Gradle
#        run: ./gradlew publish closeAndReleaseRepository
#        env:
#          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
#          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
